config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'session/new' => 'session#new'
  post "/session"      => "session#create"
  get  "/logout"       => "session#destroy"
  get '/callback', to: 'dashboard#index'
  
  resources :users
  resources :cars do 
    resources :alerts
    resources :dashboard, only: [:index]
  end

end

app/models/alert.rb
# == Schema Information
#
# Table name: alerts
#
#  id               :integer          not null, primary key
#  car_id           :integer
#  diagnostic_codes :string(255)
#  repair_status    :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#

class Alert < ActiveRecord::Base
  belongs_to :car

end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id              :integer          not null, primary key
#  user_id         :integer
#  name            :string(255)
#  make            :string(255)
#  model           :string(255)
#  year            :integer
#  starting_milage :integer
#  vin_number      :string(255)
#  image_url       :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class Car < ActiveRecord::Base
  belongs_to :user
  has_many :alerts


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string(255)      not null
#  last_name       :string(255)      not null
#  email           :string(255)      not null
#  is_admin        :boolean          default(FALSE)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  has_secure_password
  has_many :cars


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present? 
  end

  def require_admin
    if logged_in? && current_user.admin
      return true 
    else
      flash[:error] = "Restricted Access. Please login as Admin to access."
      redirect_to root_path
    end
  end

  helper_method(:current_user, :logged_in?, :require_admin)
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = current_user.cars
  end

  def new
    @user = current_user
    @car = Car.new
    response = connected_vehicles = HTTParty.get('https://api.carvoyant.com/v1/api/vehicle/',:headers => { "Authorization" => "Bearer jqrqp8hkmwy4wxpdwjjrq5mn"})
    @connected_vehicles = response["vehicle"]

  end

  def create
    @user = User.find(params["car"]["user_id"].to_i)
    @car = Car.new(car_params)
    @user.cars << @car
    if @car.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    if @car.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def destroy
    car = Car.find(params[:id])
    car.destroy
    redirect_to user_path(current_user)
  end

  private

  def car_params
    params.require(:car).permit(
      :user_id,
      :name,
      :make,
      :model,
      :year,
      :starting_milage,
      :image_url,
      :id
      )
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @cars = current_user.cars
    @car = Car.find(params[:car_id])
    @user = current_user
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    #1) Find a user by their email address and set that user = user
    user = User.find_by(email: params[:email])
    #2) if user and the user is able to authenticate by entering the correct password
    if user && user.authenticate(params[:password])
      #3)Set the user.id = to the session id
      session[:user_id] = user.id
      #4) redirect to root_path
      redirect_to user_path(session[:user_id])
    else
      #5)Else, rerender the page
      render :new
    end
  end

  def destroy
    #1)Set the session id = nil
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 

  def index
    users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = current_user
    @cars = current_user.cars

    if !logged_in?
      redirect_to root_path(@user)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
      )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_form.html.erb
<!-- car fields -->
<%= form_for(@car) do |f| %>
  <%= f.label(:name) %>  
  <%= f.text_field(:name) %>  
  <%= f.label(:make) %>  
  <%= f.text_field(:make) %>  
  <%= f.label(:model) %>  
  <%= f.text_field(:model) %> 
  <%= f.label(:year) %>  
  <%= f.number_field(:year) %>  
  <%= f.label(:starting_milage) %>  
  <%= f.number_field(:starting_milage) %>  
  <%= f.label(:image_url) %>  
  <%= f.text_field(:image_url) %>
  <%= f.hidden_field(:user_id, :value => @user.id) %>
  <%= f.hidden_field(:id) %>
  <%= f.submit %>
<% end %>

app/views/cars/edit.html.erb
<h1>Edit Your Car</h1>

<!-- car fields -->
<%= form_for(@car) do |f| %>
  <%= f.label(:name) %>  
  <%= f.text_field(:name) %>  
  <%= f.label(:make) %>  
  <%= f.text_field(:make) %>  
  <%= f.label(:model) %>  
  <%= f.text_field(:model) %> 
  <%= f.label(:year) %>  
  <%= f.number_field(:year) %>  
  <%= f.label(:starting_milage) %>  
  <%= f.number_field(:starting_milage) %>  
  <%= f.label(:image_url) %>  
  <%= f.text_field(:image_url) %>
  <%= f.submit %>
<% end %>

app/views/cars/index.html.erb
<h1>All of This User's Cars</h1>

<ul>
  <li>
    <% @cars.each do |car|%>
      <%= car.make %>
    <% end %>
  </li>
</ul>

app/views/cars/new.html.erb
<h1>Create a New Car</h1>
  <div id="carvoyant_link">
   <button id="carvoyant_link">Link from Carvoyant</button>
  </div>

  <div class="carvoyant_results">
    <select name="select" id="carvoyant_dropdown">
      <!-- <option value="value1">Value 1</option>  -->
    </select>
  </div>



<%= render partial: "form", locals: {car: @car} %>

app/views/cars/show.html.erb
<h1>Show Page for A Specific Car</h1>

app/views/dashboard/index.html.erb
<%= content_tag :div, class: "temp_information", data: {car: @car} do %>
<% end %>

<div class="map seven columns" id="map-canvas">
</div>

<div class="car_profile seven columns" id="car_profile">
  <div class="car_image three columns" id="car_image">
    <img src="<%= @car.image_url %>">
  </div>
  
  <div class="car_profile_info four columns" id="car_profile_info">
    <h3><%= @car.name %></h3>
    <button id="update_errors">Run Diagnostic</button>
    <p><strong>Make:</strong><%= @car.make %> <strong>Model:</strong><%= @car.model %> <strong>Year:</strong><%= @car.year  %></p>
    <p><strong>Milage:</strong><%= @car.starting_milage %></p>
  </div>

  <div class="user_profile_info four columns" id="user_profile_info">    
  </div>
<!--   TODO: Make these both dynamic tables -->
  <div class="current_error_codes four columns" id="current_error_codes">
    <h5>Current Error Codes</h5>
    <ol id="error_codes_list">
    </ol>
  </div>
<div class="past_error_codes four columns" id="past_error_codes">
  <h5>Past Error Codes</h5>
    <ol>
      <li>Past Error Code 1</li>
      <li>Past Error Code 2</li>
      <li>Past Error Code 3</li>
    </ol>
  </div>
</div>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InTheShopApp</title>
    <meta name="description" content="Enter description info here">
    <meta name="author" content="Enter author info here">
    <link href='http://fonts.googleapis.com/css?family=Radley' rel='stylesheet' type='text/css'>

    <!-- Google Maps Specific Meta ============================================= -->
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

    <!-- Mobile Specific Meta ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?libraries=places,geometry&sensor=false">
  </script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<h1>A Healthy Car Is A Happy Car!</h1>

<div class="forms">
  <%= form_tag("/session", method: "post") do %>
    <%= label_tag(:email) %>
    <%= text_field_tag(:email) %>
    <%= label_tag(:password) %>
    <%= password_field_tag(:password) %>
    <%= submit_tag("Login") %>
  <% end %>
</div>

app/views/users/_form.html.erb
<!-- user fields -->
<%= form_for(@user) do |f| %>
  <%= f.label(:first_name) %>  
  <%= f.text_field(:first_name) %>
  <%= f.label(:last_name) %>
  <%= f.text_field(:last_name) %>
  <%= f.label(:email) %>
  <%= f.email_field(:email) %>
  <!-- password fields -->
  <%= f.label(:password) %>
  <%= f.password_field(:password) %>
  <%= f.label(:password_confirmation) %>
  <%= f.password_field(:password_confirmation) %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Account</h1>

  <%= render partial: "form", locals: {user: @user} %>

app/views/users/new.html.erb
<h1>Create a New Account</h1>

<!-- form_for(a model) -->
<%= form_for(@user) do |f| %>
  <%= f.label(:first_name) %>  
  <%= f.text_field(:first_name) %>
  <%= f.label(:last_name) %>
  <%= f.text_field(:last_name) %>
  <%= f.label(:email) %>
  <%= f.email_field(:email) %>
  <!-- these input controls will obscure the password -->
  <%= f.label(:password) %>
  <%= f.password_field(:password) %>
  <%= f.label(:password_confirmation) %>
  <%= f.password_field(:password_confirmation) %>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>HomePage</h1>
  <h4>Welcome, <%= current_user.first_name%></h4>

<% if logged_in? %>
<div class="non_dashboard_container">

  <div id="account_settings" class="seven columns"><strong>Account Settings</strong>
    <p><%= link_to "Edit Account", edit_user_path(@user.id) %></p>
    <p><%= link_to "Delete Account", user_path(@user.id), :method => "delete" %></p>
  </div>

  <div id="add_car" class="seven columns"><strong>Add New Vehicle To Account</strong>
    <p><%= link_to "Track New Car", new_car_path %></p>
  </div>

  <div id="active_cars"><strong>Active Vehicles</strong>
    <ul id="car_display" class="three columns">
        <% @cars.each do |car|%>
      <li>
          <p><%= car.name %> || <%= car.make %>, <%= car.model %></p>
          <a href="<%= car_dashboard_index_path(car) %>" id="dashboard_link">
            <img src="<%= car.image_url %>">
          </a>
          <p><%= link_to "Edit Car", edit_car_path(car) %> || <%= link_to "Delete Car", car_path(car), :method => "delete" %></p>
        <% end %>
      </li>
    </ul>
  <% else %>
    <% redirect_to root_path %>
  <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="homepage_containter">
  <div class="eight columns header" id="homepage_banner">
    <span class="title">In the Shop</span>
  </div>
  <div id="nav" class="eight columns">
    <ul id="center">
      <li><a href="http://www.amazon.com/s/ref=nb_sb_ss_c_0_3?url=search-alias%3Dautomotive&field-keywords=odb2%20bluetooth&sprefix=odb%2Caps%2C195" target="_blank">Get Connected</a></li> ||
      <li><a href="http://www.carvoyant.com/getcarsconnected/" target="_blank">Our Partners</a></li> ||
      <li><a href="/users/new">Sign-up</a></li></li> ||
      <li><a href="/session/new">Login</a></li></li>
    </ul>
  </div>
</div>
<div id="main">
  <div id="headerImage" class="sixteen columns">
    <img src="<%= asset_path('shutterstock_162588092.jpg') %>">
  </div>
</div>